name: Terraform Validation

on:
  pull_request:
    paths:
      - "flake.*"
      - "terraform/**"
      - ".github/workflows/checks.yaml"
  push:
    paths:
      - "flake.*"
      - "terraform/**"
      - ".github/workflows/checks.yaml"

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run Formatter
        run: nix fmt -- --ci

  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Validate
        working-directory: terraform
        run: nix develop --impure --command terraform validate
