name: Formatting & Validation

on:
  push:
    paths:
      - "flake.*"
      - "terraform/**"
      - ".github/workflows/checks.yaml"

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main

        # TODO - Add Statix, deadnix and any other format checks to flake checks.
      - name: Run Format Checks
        run: nix flake check --impure --allow-import-from-derivation --accept-flake-config --no-write-lock-file

  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Validate
        working-directory: terraform
        run: nix develop --impure --command "terraform validate"
